#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""Pipecat_RE_Agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Grok (LLM)
- Inworld (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

import aiohttp
from system_prompt import SYSTEM_PROMPT
from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import LLMRunFrame, TranscriptionMessage, TranscriptionUpdateFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.processors.transcript_processor import TranscriptProcessor
from pipecat.runner.types import RunnerArguments
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.openrouter.llm import OpenRouterLLMService
from pipecat.services.inworld.tts import InworldTTSService
from pipecat.transports.base_transport import BaseTransport
from pipecat.transports.daily.transport import DailyParams, DailyTransport
from pipecat_tail.observer import TailObserver
from pipecat_whisker import WhiskerObserver
from twilio.rest import Client

from server_utils import AgentRequest

load_dotenv(override=True)


async def run_bot(transport: BaseTransport, request: AgentRequest) -> None:
    """Run the voice bot with the given parameters.

    Args:
        transport: The Daily transport instance
        request: The agent request containing the call details
    """
    logger.info("Starting bot")

    async with aiohttp.ClientSession() as session:
        # Speech-to-Text service
        stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

        # Text-to-Speech service
        tts = InworldTTSService(
            api_key=os.getenv("INWORLD_API_KEY"),
            aiohttp_session=session,
            voice_id=os.getenv("INWORLD_VOICE_ID"),
        )

        # LLM service
        llm = OpenRouterLLMService(model="x-ai/grok-4-fast", api_key=os.getenv("OPENROUTER_API_KEY"))

        messages = [
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
        ]

        context = LLMContext(messages)
        context_aggregator = LLMContextAggregatorPair(context)

        # Transcription processor
        transcript_processor = TranscriptProcessor()

        # Pipeline - assembled from reusable components
        pipeline = Pipeline(
            [
                transport.input(),
                stt,
                transcript_processor.user(),
                context_aggregator.user(),
                llm,
                tts,
                transport.output(),
                transcript_processor.assistant(),
                context_aggregator.assistant(),
            ]
        )

        task = PipelineTask(
            pipeline,
            params=PipelineParams(
                enable_metrics=True,
                enable_usage_metrics=True,
                audio_in_sample_rate=8000,
                audio_out_sample_rate=8000,
            ),
            observers=[
                WhiskerObserver(pipeline),
                TailObserver(),
            ],
        )

        @transport.event_handler("on_dialin_ready")
        async def on_dialin_ready(transport, sip_endpoint):
            logger.info(f"Forwarding call {request.call_sid} to {request.sip_uri}")

            try:
                twilio_client = Client(
                    os.getenv("TWILIO_ACCOUNT_SID"), os.getenv("TWILIO_AUTH_TOKEN")
                )

                # Update the Twilio call with TwiML to forward to the Daily SIP endpoint
                twilio_client.calls(request.call_sid).update(
                    twiml=f"<Response><Dial><Sip>{request.sip_uri}</Sip></Dial></Response>"
                )
                logger.info("Call forwarded successfully")
            except Exception as e:
                logger.error(f"Failed to forward call: {str(e)}")
                await task.cancel()

        @transport.event_handler("on_dialin_error")
        async def on_dialin_error(transport, data):
            logger.error(f"Dial-in error: {data}")
            await task.cancel()

        @transport.event_handler("on_client_connected")
        async def on_client_connected(transport, client):
            logger.info("Client connected")
            await task.queue_frame(LLMRunFrame())

        @transport.event_handler("on_client_disconnected")
        async def on_client_disconnected(transport, client):
            logger.info("Client disconnected")
            await task.cancel()

        @transcript_processor.event_handler("on_transcript_update")
        async def on_transcript_update(
            processor: TranscriptProcessor, frame: TranscriptionUpdateFrame
        ):
            for msg in frame.messages:
                if isinstance(msg, TranscriptionMessage):
                    timestamp = f"[{msg.timestamp}] " if msg.timestamp else ""
                    line = f"{timestamp}{msg.role}: {msg.content}"
                    logger.info(f"Transcript: {line}")

        runner = PipelineRunner(handle_sigint=False)

        await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    try:
        request = AgentRequest.model_validate(runner_args.body)

        transport = DailyTransport(
            request.room_url,
            request.token,
            "Twilio + Daily SIP Bot",
            params=DailyParams(
                audio_in_enabled=True,
                audio_out_enabled=True,
                vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.2)),
                turn_analyzer=LocalSmartTurnAnalyzerV3(),
            ),
        )

        await run_bot(transport, request)

    except Exception as e:
        logger.error(f"Error running bot: {e}")
        raise e


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
